#cleanup

rm -rf obj_dir
rm -f lfsr.vcd

#Run the verilator to translate .sv (Verilog) into c++, including c++ testbench

verilator -Wall --cc --trace lfsr.sv --exe lfsr_tb.cpp

#build c++ project automaticlaly, using "make", generated by verilator

make -j -C obj_dir/ -f Vlfsr.mk Vlfsr

#run executable

obj_dir/Vlfsr