#cleanup

rm -rf obj_dir
rm -f f1seq.vcd

#Run the verilator to translate .sv (Verilog) into c++, including c++ testbench

verilator -Wall --cc --trace f1seq.sv --exe f1_fsm_tb.cpp

#build c++ project automaticlaly, using "make", generated by verilator

make -j -C obj_dir/ -f Vf1seq.mk Vf1seq

#run executable

obj_dir/Vf1seq